sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- node
script:
- npm run test-ci
- npm run coverage-ci
- npm run bundle
deploy:
# versions without suffixes are published with 'latest' tag
- provider: npm
  skip_cleanup: true
  edge: true
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  tag: latest
  on:
    condition: "$TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+$"
    repo: arusak/record-player
# versions with suffixes (-0, -pre, -rc1) are published with 'next' tag
- provider: npm
  skip_cleanup: true
  edge: true
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  tag: next
  on:
    condition: "$TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+-[0-9]+$"
    repo: arusak/record-player
