sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- node
script:
- npm run test-ci
- npm run coverage-ci
- npm run build-ci
before_deploy:
- cd dist
deploy:
  provider: npm
  edge: true
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: arusak/record-player
